CREATE TABLE A(SNAME varchar(10), NUM INT(2));
CREATE TABLE B(NUM INT(2),GRADE VARCHAR(3));
INSERT INTO A VALUES('ABC',10);
INSERT INTO A VALUES('XYZ',11);
INSERT INTO A VALUES('PQR',12);
INSERT INTO A VALUES('MNO',14);
COMMIT;
INSERT INTO B VALUES(11,'A');
INSERT INTO B VALUES(12,'B');
INSERT INTO B VALUES(13,'C');
INSERT INTO B VALUES(15,'B');
COMMIT;

select num from A union all select num from B;